name: Build image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora-minimal:39

    steps:
      - name: Install dependencies
        run: dnf5 install -y git make gcc parted vboot-utils golang

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup PATH
        run: |
          echo "PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV

      - name: Install u-root
        run: go install github.com/u-root/u-root@latest

      - name: Build image
        run: make -j$(nproc)
