name: Build cr-boot

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora-minimal:39

    steps:
      - name: Install dependencies
        run: |
          dnf5 update -y
          dnf5 install -y git automake make gcc flex bison parted vboot-utils golang xz

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup PATH
        run: echo "PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV

      - name: Install u-root
        run: go install github.com/u-root/u-root@latest

      - name: Build cr-boot
        run: |
          cp kernel.config kernel/.config
          make -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cr-boot
          path: build
